[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
insurance_fund = "2MN1Dbnu7zM9Yj4ougn6ZCNNKevrSvi9AR56iawzkye8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/insurance-fund.ts"
test-no-slash = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/scenarios/no-slash.ts"
test-sdk = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/restaking-sdk.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
[[test.validator.clone]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
